import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../data/models/animal_model.dart';
import '../providers/animal_provider.dart';

class AddAnimalScreen extends StatefulWidget {
  const AddAnimalScreen({super.key});

  @override
  State<AddAnimalScreen> createState() => _AddAnimalScreenState();
}

class _AddAnimalScreenState extends State<AddAnimalScreen> {
  final _formKey = GlobalKey<FormState>();
  
  // Controllers
  final _tagIdController = TextEditingController();
  final _nameController = TextEditingController();
  final _breedController = TextEditingController();
  final _dobController = TextEditingController();
  final _weightController = TextEditingController();
  final _milkCapacityController = TextEditingController(); // New
  final _lastVaccinationDateController = TextEditingController(); // New
  final _photoUrlController = TextEditingController(); // New
  final _notesController = TextEditingController();

  // Selected Values
  String _selectedSpecies = 'Cow';
  String _selectedSex = 'Female';
  String _selectedHealthStatus = 'Healthy';
  String _selectedProductionStatus = 'Milking';
  DateTime? _selectedDate;
  DateTime? _lastVaccinationDate; // New

  final List<String> _speciesList = ['Cow', 'Buffalo', 'Goat', 'Sheep', 'Other'];
  final List<String> _healthStatusList = ['Healthy', 'Sick', 'Treatment', 'Pregnant'];
  final List<String> _productionStatusList = ['Milking', 'Dry', 'Calf', 'None'];

  Future<void> _selectDate(BuildContext context, {bool isVaccination = false}) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() {
        if (isVaccination) {
          _lastVaccinationDate = picked;
          _lastVaccinationDateController.text = DateFormat('yyyy-MM-dd').format(picked);
        } else {
          _selectedDate = picked;
          _dobController.text = DateFormat('yyyy-MM-dd').format(picked);
        }
      });
    }
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final newAnimal = Animal(
        id: '', // Will be generated by backend
        tagId: _tagIdController.text,
        name: _nameController.text,
        species: _selectedSpecies,
        breed: _breedController.text.isNotEmpty ? _breedController.text : null,
        dob: _selectedDate,
        sex: _selectedSex,
        weight: _weightController.text.isNotEmpty ? double.tryParse(_weightController.text) : null,
        healthStatus: _selectedHealthStatus,
        productionStatus: _selectedProductionStatus,
        milkCapacity: _milkCapacityController.text.isNotEmpty ? double.tryParse(_milkCapacityController.text) : null,
        lastVaccinationDate: _lastVaccinationDate,
        photos: _photoUrlController.text.isNotEmpty ? [_photoUrlController.text] : [],
        farmerId: '', // Handled by backend/provider
        notes: _notesController.text.isNotEmpty ? _notesController.text : null,
      );

      try {
        await Provider.of<AnimalProvider>(context, listen: false).addAnimal(newAnimal);
        if (mounted) {
           ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Animal added successfully!')),
          );
          context.pop();
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to add animal: $e')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add New Animal')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _tagIdController,
                decoration: const InputDecoration(labelText: 'Tag ID *'),
                validator: (value) => value!.isEmpty ? 'Please enter Tag ID' : null,
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Name *'),
                validator: (value) => value!.isEmpty ? 'Please enter Name' : null,
              ),
              const SizedBox(height: 10),
              DropdownButtonFormField<String>(
                value: _selectedSpecies,
                decoration: const InputDecoration(labelText: 'Species *'),
                items: _speciesList.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() {
                    _selectedSpecies = newValue!;
                  });
                },
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _breedController,
                decoration: const InputDecoration(labelText: 'Breed'),
              ),
              const SizedBox(height: 10),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _dobController,
                      decoration: const InputDecoration(
                        labelText: 'Date of Birth',
                        suffixIcon: Icon(Icons.calendar_today),
                      ),
                      readOnly: true,
                      onTap: () => _selectDate(context),
                    ),
                  ),
                  const SizedBox(width: 10),
                  // Simple Sex Selection
                  Expanded(
                    child: DropdownButtonFormField<String>(
                      value: _selectedSex,
                      decoration: const InputDecoration(labelText: 'Sex *'),
                      items: ['Male', 'Female'].map((String value) {
                        return DropdownMenuItem<String>(
                          value: value,
                          child: Text(value),
                        );
                      }).toList(),
                      onChanged: (newValue) {
                        setState(() {
                          _selectedSex = newValue!;
                        });
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _weightController,
                decoration: const InputDecoration(labelText: 'Weight (kg)'),
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 10),
              DropdownButtonFormField<String>(
                value: _selectedHealthStatus,
                decoration: const InputDecoration(labelText: 'Health Status'),
                items: _healthStatusList.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() {
                    _selectedHealthStatus = newValue!;
                  });
                },
              ),
              const SizedBox(height: 10),
              const SizedBox(height: 10),
               DropdownButtonFormField<String>(
                value: _selectedProductionStatus,
                decoration: const InputDecoration(labelText: 'Production Status'),
                items: _productionStatusList.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() {
                    _selectedProductionStatus = newValue!;
                  });
                },
              ),
              const SizedBox(height: 10),
              // New Fields for Module D
              TextFormField(
                controller: _milkCapacityController,
                decoration: const InputDecoration(labelText: 'Milk Capacity (Liters/Day)'),
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _lastVaccinationDateController,
                decoration: const InputDecoration(
                  labelText: 'Last Vaccination Date',
                  suffixIcon: Icon(Icons.vaccines),
                ),
                readOnly: true,
                onTap: () => _selectDate(context, isVaccination: true),
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _photoUrlController,
                decoration: const InputDecoration(labelText: 'Photo URL (Optional)'),
                keyboardType: TextInputType.url,
              ),
               const SizedBox(height: 10),
              TextFormField(
                controller: _notesController,
                decoration: const InputDecoration(labelText: 'Notes'),
                maxLines: 3,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitForm,
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 50),
                ),
                child: const Text('Save Animal'),
              ),
            ],
          ),
        ),
      ),
    );
  }
  
  @override
  void dispose() {
    _tagIdController.dispose();
    _nameController.dispose();
    _breedController.dispose();
    _dobController.dispose();
    _weightController.dispose();
    _milkCapacityController.dispose();
    _lastVaccinationDateController.dispose();
    _photoUrlController.dispose();
    _notesController.dispose();
    super.dispose();
  }
}
